// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import "./WrappedEMBR.sol";

/**
 * @title EmberchainBridge
 * @notice Base-side bridge contract for the EMBR ↔ wEMBR bridge.
 *
 * Flow A — EMBR chain → Base (bridging IN to Base):
 *   1. User locks native EMBR on the EMBR chain via EmberBridge.sol.
 *   2. The relayer detects the BridgeOut event on the EMBR chain.
 *   3. Relayer calls bridgeIn() here, which mints wEMBR to the recipient.
 *
 * Flow B — Base → EMBR chain (bridging OUT of Base):
 *   1. User calls bridgeOut() here with their wEMBR amount and EMBR recipient address.
 *   2. This contract burns the wEMBR.
 *   3. The relayer detects the BridgeOut event and calls releaseEMBR() on EmberBridge.sol.
 *
 * Replay protection: every cross-chain operation has a unique nonce. Nonces are
 * tracked in usedNonces and can never be reused, surviving any number of restarts.
 */
contract EmberchainBridge is Ownable, ReentrancyGuard {
    WrappedEMBR public immutable wEMBR;
    address public relayer;

    /// @dev nonce → used; prevents the same cross-chain message from being processed twice
    mapping(uint256 => bool) public usedNonces;

    event BridgeIn(address indexed recipient, uint256 amount, uint256 indexed nonce);
    event BridgeOut(address indexed sender, string embrRecipient, uint256 amount, uint256 indexed nonce);
    event RelayerUpdated(address indexed oldRelayer, address indexed newRelayer);

    modifier onlyRelayer() {
        require(msg.sender == relayer, "Bridge: caller is not the relayer");
        _;
    }

    constructor(address _wEMBR, address _relayer) Ownable(msg.sender) {
        require(_wEMBR != address(0), "Bridge: zero wEMBR address");
        require(_relayer != address(0), "Bridge: zero relayer address");
        wEMBR = WrappedEMBR(_wEMBR);
        relayer = _relayer;
    }

    /**
     * @notice Mint wEMBR to a recipient after EMBR was locked on the EMBR chain.
     *         Called exclusively by the relayer; nonce ensures idempotency.
     */
    function bridgeIn(
        address recipient,
        uint256 amount,
        uint256 nonce
    ) external onlyRelayer nonReentrant {
        require(recipient != address(0), "Bridge: zero recipient");
        require(amount > 0, "Bridge: zero amount");
        require(!usedNonces[nonce], "Bridge: nonce already used");

        usedNonces[nonce] = true;
        wEMBR.mint(recipient, amount);

        emit BridgeIn(recipient, amount, nonce);
    }

    /**
     * @notice Burn wEMBR and emit an event so the relayer can release native EMBR
     *         on the EMBR chain.
     * @param amount     Amount of wEMBR to bridge back.
     * @param embrRecipient  The EMBR chain address (hex string) that will receive the unlocked EMBR.
     * @param nonce      Unique nonce generated by the caller for this bridge request.
     *                   The relayer uses this to match the Base event to the EMBR chain release.
     */
    function bridgeOut(
        uint256 amount,
        string calldata embrRecipient,
        uint256 nonce
    ) external nonReentrant {
        require(amount > 0, "Bridge: zero amount");
        require(bytes(embrRecipient).length > 0, "Bridge: empty recipient");
        require(!usedNonces[nonce], "Bridge: nonce already used");

        usedNonces[nonce] = true;
        wEMBR.burn(msg.sender, amount);

        emit BridgeOut(msg.sender, embrRecipient, amount, nonce);
    }

    /**
     * @notice Update the relayer address. Only owner.
     */
    function setRelayer(address newRelayer) external onlyOwner {
        require(newRelayer != address(0), "Bridge: zero address");
        emit RelayerUpdated(relayer, newRelayer);
        relayer = newRelayer;
    }
}
